config/routes.rb
LizzaCollab::Application.routes.draw do
  resources :infinite_shelters

  root to: 'infinite_shelters#index'

  match '/venue', to: 'infinite_shelters#venue'
  match '/tag', to: 'infinite_shelters#tag'
  match '/gallery', to: 'infinite_shelters#gallery'
  match '/article', to: 'infinite_shelters#article'
  match '/aphorism', to: 'infinite_shelters#aphorism'
  match '/people', to: 'infinite_shelters#people'
  match '/city', to: 'infinite_shelters#city'
  match '/new', to: 'infinite_shelters#new'

end

app/models/infinite_shelter.rb
class InfiniteShelter < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/infinite_shelters_controller.rb
class InfiniteSheltersController < ApplicationController
  # GET /infinite_shelters
  # GET /infinite_shelters.json
  def index

  end

  def venue

  end

  def tag

  end  

  def gallery

  end

  def article

  end  

  def aphorism

  end

  def people

  end   

  def city

  end        

  def new

  end   
end

app/helpers/application_helper.rb
module ApplicationHelper  

	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Infinite Shelter"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/infinite_shelters_helper.rb
module InfiniteSheltersHelper
end

app/views/infinite_shelters/_form.html.haml
= form_for @infinite_shelter do |f|
  -if @infinite_shelter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@infinite_shelter.errors.count, "error")} prohibited this infinite_shelter from being saved:"
      %ul
        - @infinite_shelter.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/infinite_shelters/aphorism.html.haml
= provide(:title, 'Aphorism')
%h1 Infinite Shelter Aphorism Page
%p You can edit this at app/views/aphorism.html.haml

app/views/infinite_shelters/article.html.haml
= provide(:title, 'Article')
%h1 Infinite Shelter Article Page
%p You can edit this at app/views/article.html.haml

app/views/infinite_shelters/city.html.haml
= provide(:title, 'City')
%h1 Infinite Shelter City Page
%p You can edit this at app/views/city.html.haml

app/views/infinite_shelters/edit.html.haml
%h1 Editing infinite_shelter

= render 'form'

= link_to 'Show', @infinite_shelter
\|
= link_to 'Back', infinite_shelters_path

app/views/infinite_shelters/gallery.html.haml
= provide(:title, 'Gallery')
%h1 Infinite Shelter Gallery Page
%p You can edit this at app/views/gallery.html.haml

app/views/infinite_shelters/index.html.haml
= provide(:title, 'Home')
%h1 Infinite Shelter Pages
%ul
	%li 
		%a{:href => venue_path }Venue

app/views/infinite_shelters/new.html.haml
= provide(:title, 'New')
%h1 Infinite Shelter New Page
%p You can edit this at app/views/new.html.haml

app/views/infinite_shelters/people.html.haml
= provide(:title, 'People')
%h1 Infinite Shelter People Page
%p You can edit this at app/views/people.html.haml

app/views/infinite_shelters/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_infinite_shelter_path(@infinite_shelter)
\|
= link_to 'Back', infinite_shelters_path

app/views/infinite_shelters/tag.html.haml
= provide(:title, 'Tag')
%h1 Infinite Shelter Tag Page
%p You can edit this at app/views/tag.html.haml

app/views/infinite_shelters/venue.html.haml
= provide(:title, 'Venue')
%div#content
	%div.container
		%div#main_content
			%h2 Venue Name - Venue Type - City
			= image_tag("venue_image.png")
			%p#description Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			%div#map
				%canvas 
					
					
			%ul
				%li 
					%a{:href => "#"}Post Event
				%li
					%a{:href => "#"}Next Event
			%div#rating
				%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
				%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
				%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled", :checked => "checked"}/
				%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
				%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
			%div#other_venue
				%h3 Other Venue
				%ul
					%li
						= link_to image_tag("venue_image_thumb.png"), "#"
						%div#rating
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled", :checked => "checked"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
					%li
						= link_to image_tag("venue_image_thumb.png"), "#"
						%div#rating
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled", :checked => "checked"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
					%li
						= link_to image_tag("venue_image_thumb.png"), "#"
						%div#rating
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled", :checked => "checked"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
					%li
						= link_to image_tag("venue_image_thumb.png"), "#"
						%div#rating
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled", :checked => "checked"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
							%input{:name => "star3", :type => "radio", :class => "star", :disabled => "disabled"}/
		%div#sidebar
			%p google ad
%footer
	%p Infinite Shelter 2012
	%ul
		%li
			%a{:href => "#"}Terms of Use
		%li
			%a{:href => "#"}Privacy Policy

app/views/layouts/_header.html.haml
%header
	%div.container
		= link_to image_tag("is_logo.png"), root_path
		%nav{:id => "main-nav"}
			%ul
				%li{:class => "first"}
					= link_to "Home", root_path
				%li 
					= link_to "Tag", tag_path
				%li 
					= link_to "Gallery", gallery_path
				%li 
					= link_to "Article", article_path
				%li 
					= link_to "Aphorism", aphorism_path
				%li 
					= link_to "People", people_path
				%li 
					= link_to "City", city_path
				%li{:class => "last"} 
					= link_to "New", new_path
		%nav{:id => "user-menu"}
			%ul
				%li
					= link_to "Register", root_path
				%li{:class => "last"}
					= link_to "Login", root_path

app/views/layouts/_shim.html.haml
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title 
			= full_title(yield(:title)) 
		= stylesheet_link_tag :application
		= javascript_include_tag :application
		= csrf_meta_tags
		= render 'layouts/shim'
	%body
		= render 'layouts/header'
		= yield